export const ExampleBookingData = [
  {
    territory: "territory name 1",
    cabinets: [
      {
        cabinet: "100",
        events: [
          {
            eventid: "100_1",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 9, 0),
            eventEndTime: new Date(2023, 2, 26, 10, 30),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "100_2",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 13, 25),
            eventEndTime: new Date(2023, 2, 26, 14, 0),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
      {
        cabinet: "603",
        events: [
          {
            eventid: "603_1",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 16, 0),
            eventEndTime: new Date(2023, 2, 26, 16, 30),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "603_1",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 16, 40),
            eventEndTime: new Date(2023, 2, 26, 17, 20),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "2",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 17, 35),
            eventEndTime: new Date(2023, 2, 26, 18, 0),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "3",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 10, 15),
            eventEndTime: new Date(2023, 2, 26, 11, 20),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
    ],
  },
  {
    territory: "territory name 2",
    cabinets: [
      {
        cabinet: "002",
        events: [
          {
            eventid: "002_1",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 17, 15),
            eventEndTime: new Date(2023, 2, 26, 18, 0),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "2",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 16, 0),
            eventEndTime: new Date(2023, 2, 26, 17, 10),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "3",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 9, 15),
            eventEndTime: new Date(2023, 2, 26, 11, 20),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
      {
        cabinet: "238",
        events: [
          {
            eventid: "238_1",
            eventName: "bla-bla1",
            eventStartTime: new Date(2023, 2, 26, 10, 15),
            eventEndTime: new Date(2023, 2, 26, 10, 30),
            creator: "name name name",
            numberOfPeople: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
    ],
  },
];
