export const ExampleBookingData = [
  {
    territory: "Улица1",
    cabinets: [
      {
        cabinet: "100",
        events: [
          {
            eventid: "100_1",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 9, 5),
            eventEndTime: new Date(2023, 2, 26, 13, 0),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
      {
        cabinet: "603",
        events: [
          {
            eventid: "603_1",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 16, 0),
            eventEndTime: new Date(2023, 2, 26, 16, 30),
            creator: "name name name",
            participants: 50,
            wardrobeService: true,
            foodService: false,
            tableWithName: true,
          },
          {
            eventid: "603_2",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 16, 40),
            eventEndTime: new Date(2023, 2, 26, 17, 20),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "603_3",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 17, 35),
            eventEndTime: new Date(2023, 2, 26, 18, 0),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "603_4",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 10, 15),
            eventEndTime: new Date(2023, 2, 26, 11, 20),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
    ],
  },
  {
    territory: "Улица2",
    cabinets: [
      {
        cabinet: "002",
        events: [
          {
            eventid: "002_1",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 17, 10),
            eventEndTime: new Date(2023, 2, 26, 18, 0),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "002_2",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 16, 0),
            eventEndTime: new Date(2023, 2, 26, 17, 10),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "002_3",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 9, 15),
            eventEndTime: new Date(2023, 2, 26, 11, 20),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
      {
        cabinet: "238",
        events: [
          {
            eventid: "238_1",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 10, 15),
            eventEndTime: new Date(2023, 2, 26, 10, 30),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "238_1",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 10, 30),
            eventEndTime: new Date(2023, 2, 26, 11, 0),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
          {
            eventid: "238_1",
            eventName: "EventName",
            eventStartTime: new Date(2023, 2, 26, 17, 0),
            eventEndTime: new Date(2023, 2, 26, 19, 30),
            creator: "name name name",
            participants: 50,
            wardrobeService: false,
            foodService: false,
            tableWithName: false,
          },
        ],
      },
    ],
  },
];
